Add support for SSL policy
gruntwork-io/terraform-google-static-assets pull request #11
Opened 2020-08-05 16:29 UTC by jlubawy

Depends on https://github.com/gruntwork-io/terraform-google-load-balancer/pull/15

2020-09-10 20:40 UTC, romankor commented
@jlubawy any chance you guys merge any of the PR's ?!

2020-11-05 18:57 UTC, jlubawy commented
> @jlubawy any chance you guys merge any of the PR's ?!

I'm not a member of the gruntwork team, but would also like to see these related PRs merged, they seem simple enough.

2020-11-12 07:43 UTC, robmorgan requested changes
This PR should also have an explicit test case for the `ssl_policy` functionality.

2020-11-12 07:43 UTC, robmorgan commented on modules/http-load-balancer-website/variables.tf
> +  default     = ""
```suggestion
  default     = null
```
Let's set the default to `null` for better consistency with our other modules.

2020-11-12 07:43 UTC, robmorgan commented on modules/http-load-balancer-website/variables.tf
> +  description = "Link to ssl policy. Omitted if not provided"
```suggestion
  description = "A reference to the SslPolicy resource that will be associated with the TargetHttpsProxy resource. If not set, the TargetHttpsProxy resource will not have any SSL policy configured."
```
We'll adopt the TF provider docs as its clearer to the users.

2020-12-15 17:50 UTC, jlubawy commented
> This PR should also have an explicit test case for the `ssl_policy` functionality.

@robmorgan what would the test case cover in your mind? I'm not sure I have the bandwidth to add a test case at the moment (I don't have much experience here), but I'd like to help get this PR merged.

2021-01-13 07:12 UTC, robmorgan commented
Hi @jlubawy, I'm also short on bandwidth, but am happy to review any contributions. We need a new test case to explicitly pass in an `ssl_policy` parameter so we can properly test this feature. Our tests are written using [Terratest](https://terratest.gruntwork.io). I imagine the best place to start would likely be upstream in the [terraform-google-load-balancer](https://github.com/gruntwork-io/terraform-google-load-balancer/) repo. I'd start by maybe adding a `ssl_test.go` file then copying the code from another test case. This new test case should ensure the `ssl_policy` has a value set when deploying the example.

2021-09-11 15:55 UTC, closed without merging